import { existsSync } from 'node:fs'
import { join } from 'node:path'

// Production hardening: the bridge also terminates TLS so the nginx→Bun hop is
// encrypted (no plaintext token / terminal I/O on the wire). Reuses the mkcert
// certificate generated by `pnpm certs:setup` — the same one nginx serves. dev
// (`pnpm dev`) leaves CMUX_REMOTE_TLS unset and stays on HTTP, since Vite proxies
// to localhost and there is no LAN/cross-host exposure to protect there.
const DEFAULT_CERT = join(import.meta.dir, '../../../certs/server.pem')
const DEFAULT_KEY = join(import.meta.dir, '../../../certs/server-key.pem')

export type TlsOptions = { cert: ReturnType<typeof Bun.file>; key: ReturnType<typeof Bun.file> }

function tlsEnabled(): boolean {
  const value = process.env.CMUX_REMOTE_TLS
  return value === '1' || value?.toLowerCase() === 'true'
}

export function loadTlsOptions(
  certPath: string = process.env.CMUX_TLS_CERT ?? DEFAULT_CERT,
  keyPath: string = process.env.CMUX_TLS_KEY ?? DEFAULT_KEY,
  enabled: boolean = tlsEnabled(),
): TlsOptions | undefined {
  if (!enabled) return undefined
  if (!existsSync(certPath) || !existsSync(keyPath)) {
    throw new Error(
      `CMUX_REMOTE_TLS is set but the TLS cert/key were not found (${certPath}, ${keyPath}). Run 'pnpm certs:setup'.`,
    )
  }
  return { cert: Bun.file(certPath), key: Bun.file(keyPath) }
}
